modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Kepler7894i/SpawnCheck/issues"

[[mods]]
modId = "spawncheck"
version = "${version}"
displayName = "Spawn Check"
displayURL = "https://github.com/Kepler7894i/SpawnCheck"
iconFile = "assets/spawncheck/icon.png"
authors = "Sam MacKay"
description = "Shows where mobs WILL actually spawn (not just where the block allows it) and explains why a mob can't spawn somewhere. Built for debugging mob farms."

[[dependencies.spawncheck]]
modId = "neoforge"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spawncheck]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
